/*
 * AUTO-GENERATED by tools/generate-levels.mjs from tools/specs/dawn.mjs — do not edit by hand.
 * Every level here has been brute-force verified as solvable.
 *
 * Units: logical 800x1200 board. Mirror angle "a" is in degrees.
 * par = fewest mirrors that must be turned to win (3 stars at or under par).
 */
export default {
  "id": "dawn",
  "title": "Dawn",
  "subtitle": "First light",
  "levels": [
    {
      "name": "Horizon",
      "hint": "Touch & rotate mirrors to guide the light",
      "par": 1,
      "emitters": [
        { "x": 90, "y": 260, "dx": 1, "dy": 0 }
      ],
      "mirrors": [
        { "x": 400, "y": 260, "a": 105 }
      ],
      "crystals": [
        { "x": 400, "y": 960 }
      ],
      "obstacles": []
    },
    {
      "name": "Reflection",
      "hint": "Light passes through crystals — chain them together",
      "par": 2,
      "emitters": [
        { "x": 120, "y": 1060, "dx": 0, "dy": -1 }
      ],
      "mirrors": [
        { "x": 120, "y": 250, "a": 30 },
        { "x": 680, "y": 250, "a": 150 }
      ],
      "crystals": [
        { "x": 120, "y": 650 },
        { "x": 380, "y": 770 }
      ],
      "obstacles": []
    },
    {
      "name": "Ember",
      "par": 2,
      "emitters": [
        { "x": 160, "y": 1090, "dx": 0, "dy": -1 }
      ],
      "mirrors": [
        { "x": 160, "y": 718, "a": 60 },
        { "x": 576, "y": 958, "a": 90 }
      ],
      "crystals": [
        { "x": 576, "y": 509 }
      ],
      "obstacles": []
    },
    {
      "name": "Meridian",
      "par": 2,
      "emitters": [
        { "x": 560, "y": 1090, "dx": 0, "dy": -1 }
      ],
      "mirrors": [
        { "x": 560, "y": 618, "a": 90 },
        { "x": 162, "y": 388, "a": 15 }
      ],
      "crystals": [
        { "x": 162, "y": 584 },
        { "x": 354, "y": 499 }
      ],
      "obstacles": []
    },
    {
      "name": "Anchor",
      "hint": "Gilded mirrors are fixed in place",
      "par": 1,
      "emitters": [
        { "x": 260, "y": 230, "dx": 0, "dy": 1 }
      ],
      "mirrors": [
        { "x": 260, "y": 662, "a": 30, "fixed": true },
        { "x": 676, "y": 422, "a": 120 }
      ],
      "crystals": [
        { "x": 676, "y": 575 },
        { "x": 510, "y": 518 }
      ],
      "obstacles": []
    },
    {
      "name": "Lattice",
      "par": 3,
      "emitters": [
        { "x": 720, "y": 1020, "dx": -1, "dy": 0 }
      ],
      "mirrors": [
        { "x": 168, "y": 1020, "a": 0 },
        { "x": 168, "y": 560, "a": 15 },
        { "x": 508, "y": 560, "a": 0 }
      ],
      "crystals": [
        { "x": 508, "y": 393 },
        { "x": 300, "y": 560 }
      ],
      "obstacles": []
    },
    {
      "name": "Whisper",
      "hint": "Not every mirror is needed",
      "par": 2,
      "emitters": [
        { "x": 340, "y": 1090, "dx": 0, "dy": -1 }
      ],
      "mirrors": [
        { "x": 340, "y": 498, "a": 60 },
        { "x": 513, "y": 598, "a": 165 },
        { "x": 620, "y": 880, "a": 15 }
      ],
      "crystals": [
        { "x": 125, "y": 822 },
        { "x": 340, "y": 826 }
      ],
      "obstacles": []
    },
    {
      "name": "Constellation",
      "par": 3,
      "emitters": [
        { "x": 80, "y": 400, "dx": 1, "dy": 0 }
      ],
      "mirrors": [
        { "x": 652, "y": 400, "a": 75 },
        { "x": 652, "y": 820, "a": 30 },
        { "x": 323, "y": 630, "a": 105 }
      ],
      "crystals": [
        { "x": 183, "y": 873 },
        { "x": 470, "y": 715 },
        { "x": 652, "y": 571 }
      ],
      "obstacles": []
    }
  ]
};
