/*
 * AUTO-GENERATED by tools/generate-levels.mjs from tools/specs/monolith.mjs — do not edit by hand.
 * Every level here has been brute-force verified as solvable.
 *
 * Units: logical 800x1200 board. Mirror angle "a" is in degrees.
 * par = fewest mirrors that must be turned to win (3 stars at or under par).
 */
export default {
  "id": "monolith",
  "title": "Monoliths",
  "subtitle": "Shadows stand tall",
  "levels": [
    {
      "name": "Monolith",
      "hint": "Obsidian absorbs light — route around it",
      "par": 3,
      "emitters": [
        { "x": 80, "y": 600, "dx": 1, "dy": 0 }
      ],
      "mirrors": [
        { "x": 200, "y": 600, "a": 15 },
        { "x": 200, "y": 300, "a": 75 },
        { "x": 650, "y": 300, "a": 120 }
      ],
      "crystals": [
        { "x": 650, "y": 600 },
        { "x": 420, "y": 300 }
      ],
      "obstacles": [
        { "x": 340, "y": 430, "w": 140, "h": 340 }
      ]
    },
    {
      "name": "Obelisk",
      "par": 2,
      "emitters": [
        { "x": 80, "y": 360, "dx": 1, "dy": 0 }
      ],
      "mirrors": [
        { "x": 512, "y": 360, "a": 135 },
        { "x": 692, "y": 672, "a": 60 }
      ],
      "crystals": [
        { "x": 503, "y": 672 },
        { "x": 337, "y": 360 }
      ],
      "obstacles": [
        { "x": 240, "y": 480, "w": 280, "h": 100 }
      ]
    },
    {
      "name": "Shadowline",
      "par": 3,
      "emitters": [
        { "x": 540, "y": 1090, "dx": 0, "dy": -1 }
      ],
      "mirrors": [
        { "x": 540, "y": 518, "a": 75 },
        { "x": 160, "y": 518, "a": 45 },
        { "x": 420, "y": 968, "a": 165 }
      ],
      "crystals": [
        { "x": 224, "y": 1081 },
        { "x": 295, "y": 751 }
      ],
      "obstacles": [
        { "x": 360, "y": 600, "w": 100, "h": 180 }
      ]
    },
    {
      "name": "Keystone",
      "par": 2,
      "emitters": [
        { "x": 80, "y": 320, "dx": 1, "dy": 0 }
      ],
      "mirrors": [
        { "x": 612, "y": 320, "a": 0 },
        { "x": 612, "y": 760, "a": 120, "fixed": true },
        { "x": 335, "y": 920, "a": 75 }
      ],
      "crystals": [
        { "x": 125, "y": 556 },
        { "x": 427, "y": 320 },
        { "x": 287, "y": 320 }
      ],
      "obstacles": [
        { "x": 180, "y": 440, "w": 220, "h": 120 }
      ]
    },
    {
      "name": "Colonnade",
      "par": 3,
      "emitters": [
        { "x": 80, "y": 660, "dx": 1, "dy": 0 }
      ],
      "mirrors": [
        { "x": 572, "y": 660, "a": 60 },
        { "x": 572, "y": 340, "a": 15 },
        { "x": 252, "y": 340, "a": 75 }
      ],
      "crystals": [
        { "x": 252, "y": 620 },
        { "x": 371, "y": 660 },
        { "x": 372, "y": 340 }
      ],
      "obstacles": [
        { "x": 320, "y": 400, "w": 180, "h": 100 },
        { "x": 280, "y": 940, "w": 260, "h": 100 }
      ]
    },
    {
      "name": "Eclipse",
      "par": 3,
      "emitters": [
        { "x": 80, "y": 280, "dx": 1, "dy": 0 }
      ],
      "mirrors": [
        { "x": 592, "y": 280, "a": 120 },
        { "x": 592, "y": 480, "a": 165 },
        { "x": 212, "y": 480, "a": 165 },
        { "x": 320, "y": 1060, "a": 15 }
      ],
      "crystals": [
        { "x": 212, "y": 935 },
        { "x": 365, "y": 480 }
      ],
      "obstacles": [
        { "x": 340, "y": 620, "w": 280, "h": 100 }
      ]
    },
    {
      "name": "Labyrinth",
      "par": 4,
      "emitters": [
        { "x": 80, "y": 1000, "dx": 1, "dy": 0 }
      ],
      "mirrors": [
        { "x": 472, "y": 1000, "a": 60 },
        { "x": 472, "y": 460, "a": 105 },
        { "x": 192, "y": 460, "a": 45 },
        { "x": 192, "y": 740, "a": 60 }
      ],
      "crystals": [
        { "x": 393, "y": 624 },
        { "x": 305, "y": 1000 },
        { "x": 192, "y": 591 }
      ],
      "obstacles": [
        { "x": 220, "y": 820, "w": 200, "h": 100 },
        { "x": 540, "y": 780, "w": 100, "h": 240 }
      ]
    },
    {
      "name": "Citadel",
      "par": 3,
      "emitters": [
        { "x": 80, "y": 960, "dx": 1, "dy": 0 }
      ],
      "mirrors": [
        { "x": 372, "y": 960, "a": 120, "fixed": true },
        { "x": 132, "y": 544, "a": 120 },
        { "x": 312, "y": 232, "a": 135 },
        { "x": 572, "y": 382, "a": 150 },
        { "x": 540, "y": 940, "a": 165 }
      ],
      "crystals": [
        { "x": 349, "y": 768 },
        { "x": 240, "y": 356 },
        { "x": 236, "y": 960 }
      ],
      "obstacles": [
        { "x": 620, "y": 800, "w": 80, "h": 200 },
        { "x": 220, "y": 460, "w": 140, "h": 160 }
      ]
    }
  ]
};
