/*
 * AUTO-GENERATED by tools/generate-levels.mjs from tools/specs/twin.mjs — do not edit by hand.
 * Every level here has been brute-force verified as solvable.
 *
 * Units: logical 800x1200 board. Mirror angle "a" is in degrees.
 * par = fewest mirrors that must be turned to win (3 stars at or under par).
 */
export default {
  "id": "twin",
  "title": "Twin Suns",
  "subtitle": "Two lights, one harmony",
  "levels": [
    {
      "name": "Binary",
      "hint": "Two suns — every crystal must shine",
      "par": 2,
      "emitters": [
        { "x": 80, "y": 400, "dx": 1, "dy": 0 },
        { "x": 720, "y": 800, "dx": -1, "dy": 0 }
      ],
      "mirrors": [
        { "x": 592, "y": 400, "a": 120 },
        { "x": 288, "y": 800, "a": 150 }
      ],
      "crystals": [
        { "x": 592, "y": 835 },
        { "x": 288, "y": 294 }
      ],
      "obstacles": []
    },
    {
      "name": "Confluence",
      "par": 3,
      "emitters": [
        { "x": 640, "y": 1090, "dx": 0, "dy": -1 },
        { "x": 720, "y": 460, "dx": -1, "dy": 0 }
      ],
      "mirrors": [
        { "x": 640, "y": 638, "a": 135 },
        { "x": 432, "y": 518, "a": 45 },
        { "x": 128, "y": 460, "a": 15 }
      ],
      "crystals": [
        { "x": 572, "y": 276 },
        { "x": 227, "y": 289 },
        { "x": 640, "y": 849 }
      ],
      "obstacles": []
    },
    {
      "name": "Solstice",
      "par": 3,
      "emitters": [
        { "x": 260, "y": 230, "dx": 0, "dy": 1 },
        { "x": 80, "y": 640, "dx": 1, "dy": 0 }
      ],
      "mirrors": [
        { "x": 260, "y": 482, "a": 15 },
        { "x": 658, "y": 712, "a": 120 },
        { "x": 352, "y": 640, "a": 30 }
      ],
      "crystals": [
        { "x": 658, "y": 246 },
        { "x": 352, "y": 330 },
        { "x": 516, "y": 630 }
      ],
      "obstacles": [
        { "x": 480, "y": 300, "w": 80, "h": 260 }
      ]
    },
    {
      "name": "Equinox",
      "par": 3,
      "emitters": [
        { "x": 80, "y": 700, "dx": 1, "dy": 0 },
        { "x": 720, "y": 820, "dx": -1, "dy": 0 }
      ],
      "mirrors": [
        { "x": 572, "y": 700, "a": 45 },
        { "x": 682, "y": 509, "a": 15 },
        { "x": 168, "y": 820, "a": 45, "fixed": true },
        { "x": 168, "y": 420, "a": 15 }
      ],
      "crystals": [
        { "x": 324, "y": 302 },
        { "x": 453, "y": 255 },
        { "x": 168, "y": 608 }
      ],
      "obstacles": [
        { "x": 320, "y": 480, "w": 220, "h": 80 }
      ]
    },
    {
      "name": "Aurora",
      "par": 4,
      "emitters": [
        { "x": 720, "y": 440, "dx": -1, "dy": 0 },
        { "x": 80, "y": 980, "dx": 1, "dy": 0 }
      ],
      "mirrors": [
        { "x": 248, "y": 440, "a": 90 },
        { "x": 248, "y": 780, "a": 120 },
        { "x": 392, "y": 980, "a": 120 },
        { "x": 562, "y": 686, "a": 30 }
      ],
      "crystals": [
        { "x": 628, "y": 561 },
        { "x": 677, "y": 885 },
        { "x": 248, "y": 599 },
        { "x": 418, "y": 440 }
      ],
      "obstacles": [
        { "x": 100, "y": 520, "w": 80, "h": 180 }
      ]
    },
    {
      "name": "Parallax",
      "par": 3,
      "emitters": [
        { "x": 520, "y": 1090, "dx": 0, "dy": -1 },
        { "x": 80, "y": 980, "dx": 1, "dy": 0 }
      ],
      "mirrors": [
        { "x": 520, "y": 578, "a": 165 },
        { "x": 278, "y": 438, "a": 165 },
        { "x": 652, "y": 980, "a": 15 },
        { "x": 160, "y": 580, "a": 165 }
      ],
      "crystals": [
        { "x": 364, "y": 290 },
        { "x": 652, "y": 777 },
        { "x": 393, "y": 504 }
      ],
      "obstacles": [
        { "x": 420, "y": 300, "w": 180, "h": 100 },
        { "x": 240, "y": 580, "w": 200, "h": 80 }
      ]
    },
    {
      "name": "Zenith",
      "par": 4,
      "emitters": [
        { "x": 80, "y": 1020, "dx": 1, "dy": 0 },
        { "x": 240, "y": 230, "dx": 0, "dy": 1 }
      ],
      "mirrors": [
        { "x": 432, "y": 1020, "a": 30 },
        { "x": 622, "y": 691, "a": 90, "fixed": true },
        { "x": 512, "y": 500, "a": 60 },
        { "x": 240, "y": 782, "a": 150 },
        { "x": 569, "y": 972, "a": 30 }
      ],
      "crystals": [
        { "x": 126, "y": 723 },
        { "x": 647, "y": 837 },
        { "x": 427, "y": 890 },
        { "x": 278, "y": 1020 }
      ],
      "obstacles": [
        { "x": 360, "y": 240, "w": 260, "h": 80 },
        { "x": 380, "y": 640, "w": 160, "h": 120 }
      ]
    },
    {
      "name": "Sanctuary",
      "par": 5,
      "emitters": [
        { "x": 180, "y": 230, "dx": 0, "dy": 1 },
        { "x": 180, "y": 1090, "dx": 0, "dy": -1 }
      ],
      "mirrors": [
        { "x": 180, "y": 502, "a": 75 },
        { "x": 526, "y": 302, "a": 0 },
        { "x": 526, "y": 642, "a": 75 },
        { "x": 180, "y": 838, "a": 45 },
        { "x": 380, "y": 838, "a": 165 }
      ],
      "crystals": [
        { "x": 211, "y": 642 },
        { "x": 380, "y": 679 },
        { "x": 526, "y": 521 },
        { "x": 312, "y": 426 }
      ],
      "obstacles": [
        { "x": 220, "y": 920, "w": 240, "h": 100 },
        { "x": 580, "y": 720, "w": 120, "h": 200 }
      ]
    }
  ]
};
