/*
 * AUTO-GENERATED by tools/generate-levels.mjs — do not edit by hand.
 * Change the specs in that script and run:  node tools/generate-levels.mjs
 * Every level here has been brute-force verified as solvable.
 *
 * Units: logical 800x1200 board. Mirror angle "a" is in degrees.
 * par = fewest mirrors that must be turned to win (3 stars at or under par).
 */
export const CHAPTERS = [
  {
    "id": "dawn",
    "title": "Dawn",
    "subtitle": "First light",
    "levels": [
      {
        "name": "Horizon",
        "hint": "Touch & rotate mirrors to guide the light",
        "par": 1,
        "emitters": [
          { "x": 90, "y": 260, "dx": 1, "dy": 0 }
        ],
        "mirrors": [
          { "x": 400, "y": 260, "a": 105 }
        ],
        "crystals": [
          { "x": 400, "y": 960 }
        ],
        "obstacles": []
      },
      {
        "name": "Reflection",
        "hint": "Light passes through crystals — chain them together",
        "par": 2,
        "emitters": [
          { "x": 120, "y": 1060, "dx": 0, "dy": -1 }
        ],
        "mirrors": [
          { "x": 120, "y": 250, "a": 30 },
          { "x": 680, "y": 250, "a": 150 }
        ],
        "crystals": [
          { "x": 120, "y": 650 },
          { "x": 380, "y": 770 }
        ],
        "obstacles": []
      },
      {
        "name": "Ember",
        "par": 2,
        "emitters": [
          { "x": 160, "y": 1090, "dx": 0, "dy": -1 }
        ],
        "mirrors": [
          { "x": 160, "y": 718, "a": 60 },
          { "x": 576, "y": 958, "a": 90 }
        ],
        "crystals": [
          { "x": 576, "y": 509 }
        ],
        "obstacles": []
      },
      {
        "name": "Meridian",
        "par": 2,
        "emitters": [
          { "x": 560, "y": 1090, "dx": 0, "dy": -1 }
        ],
        "mirrors": [
          { "x": 560, "y": 618, "a": 90 },
          { "x": 162, "y": 388, "a": 15 }
        ],
        "crystals": [
          { "x": 162, "y": 584 },
          { "x": 354, "y": 499 }
        ],
        "obstacles": []
      },
      {
        "name": "Anchor",
        "hint": "Gilded mirrors are fixed in place",
        "par": 1,
        "emitters": [
          { "x": 260, "y": 230, "dx": 0, "dy": 1 }
        ],
        "mirrors": [
          { "x": 260, "y": 662, "a": 30, "fixed": true },
          { "x": 676, "y": 422, "a": 120 }
        ],
        "crystals": [
          { "x": 676, "y": 575 },
          { "x": 510, "y": 518 }
        ],
        "obstacles": []
      },
      {
        "name": "Lattice",
        "par": 3,
        "emitters": [
          { "x": 720, "y": 1020, "dx": -1, "dy": 0 }
        ],
        "mirrors": [
          { "x": 168, "y": 1020, "a": 0 },
          { "x": 168, "y": 560, "a": 15 },
          { "x": 508, "y": 560, "a": 0 }
        ],
        "crystals": [
          { "x": 508, "y": 393 },
          { "x": 300, "y": 560 }
        ],
        "obstacles": []
      },
      {
        "name": "Whisper",
        "hint": "Not every mirror is needed",
        "par": 2,
        "emitters": [
          { "x": 340, "y": 1090, "dx": 0, "dy": -1 }
        ],
        "mirrors": [
          { "x": 340, "y": 498, "a": 60 },
          { "x": 513, "y": 598, "a": 165 },
          { "x": 620, "y": 880, "a": 15 }
        ],
        "crystals": [
          { "x": 125, "y": 822 },
          { "x": 340, "y": 826 }
        ],
        "obstacles": []
      },
      {
        "name": "Constellation",
        "par": 3,
        "emitters": [
          { "x": 80, "y": 400, "dx": 1, "dy": 0 }
        ],
        "mirrors": [
          { "x": 652, "y": 400, "a": 75 },
          { "x": 652, "y": 820, "a": 30 },
          { "x": 323, "y": 630, "a": 105 }
        ],
        "crystals": [
          { "x": 183, "y": 873 },
          { "x": 470, "y": 715 },
          { "x": 652, "y": 571 }
        ],
        "obstacles": []
      }
    ]
  },
  {
    "id": "monolith",
    "title": "Monoliths",
    "subtitle": "Shadows stand tall",
    "levels": [
      {
        "name": "Monolith",
        "hint": "Obsidian absorbs light — route around it",
        "par": 3,
        "emitters": [
          { "x": 80, "y": 600, "dx": 1, "dy": 0 }
        ],
        "mirrors": [
          { "x": 200, "y": 600, "a": 15 },
          { "x": 200, "y": 300, "a": 75 },
          { "x": 650, "y": 300, "a": 120 }
        ],
        "crystals": [
          { "x": 650, "y": 600 },
          { "x": 420, "y": 300 }
        ],
        "obstacles": [
          { "x": 340, "y": 430, "w": 140, "h": 340 }
        ]
      },
      {
        "name": "Obelisk",
        "par": 2,
        "emitters": [
          { "x": 80, "y": 360, "dx": 1, "dy": 0 }
        ],
        "mirrors": [
          { "x": 512, "y": 360, "a": 135 },
          { "x": 692, "y": 672, "a": 60 }
        ],
        "crystals": [
          { "x": 503, "y": 672 },
          { "x": 337, "y": 360 }
        ],
        "obstacles": [
          { "x": 240, "y": 480, "w": 280, "h": 100 }
        ]
      },
      {
        "name": "Shadowline",
        "par": 3,
        "emitters": [
          { "x": 540, "y": 1090, "dx": 0, "dy": -1 }
        ],
        "mirrors": [
          { "x": 540, "y": 518, "a": 75 },
          { "x": 160, "y": 518, "a": 45 },
          { "x": 420, "y": 968, "a": 165 }
        ],
        "crystals": [
          { "x": 224, "y": 1081 },
          { "x": 295, "y": 751 }
        ],
        "obstacles": [
          { "x": 360, "y": 600, "w": 100, "h": 180 }
        ]
      },
      {
        "name": "Keystone",
        "par": 2,
        "emitters": [
          { "x": 80, "y": 320, "dx": 1, "dy": 0 }
        ],
        "mirrors": [
          { "x": 612, "y": 320, "a": 0 },
          { "x": 612, "y": 760, "a": 120, "fixed": true },
          { "x": 335, "y": 920, "a": 75 }
        ],
        "crystals": [
          { "x": 125, "y": 556 },
          { "x": 427, "y": 320 },
          { "x": 287, "y": 320 }
        ],
        "obstacles": [
          { "x": 180, "y": 440, "w": 220, "h": 120 }
        ]
      },
      {
        "name": "Colonnade",
        "par": 3,
        "emitters": [
          { "x": 80, "y": 660, "dx": 1, "dy": 0 }
        ],
        "mirrors": [
          { "x": 572, "y": 660, "a": 60 },
          { "x": 572, "y": 340, "a": 15 },
          { "x": 252, "y": 340, "a": 75 }
        ],
        "crystals": [
          { "x": 252, "y": 620 },
          { "x": 371, "y": 660 },
          { "x": 372, "y": 340 }
        ],
        "obstacles": [
          { "x": 320, "y": 400, "w": 180, "h": 100 },
          { "x": 280, "y": 940, "w": 260, "h": 100 }
        ]
      },
      {
        "name": "Eclipse",
        "par": 3,
        "emitters": [
          { "x": 80, "y": 280, "dx": 1, "dy": 0 }
        ],
        "mirrors": [
          { "x": 592, "y": 280, "a": 120 },
          { "x": 592, "y": 480, "a": 165 },
          { "x": 212, "y": 480, "a": 165 },
          { "x": 320, "y": 1060, "a": 15 }
        ],
        "crystals": [
          { "x": 212, "y": 935 },
          { "x": 365, "y": 480 }
        ],
        "obstacles": [
          { "x": 340, "y": 620, "w": 280, "h": 100 }
        ]
      },
      {
        "name": "Labyrinth",
        "par": 4,
        "emitters": [
          { "x": 80, "y": 1000, "dx": 1, "dy": 0 }
        ],
        "mirrors": [
          { "x": 472, "y": 1000, "a": 60 },
          { "x": 472, "y": 460, "a": 105 },
          { "x": 192, "y": 460, "a": 45 },
          { "x": 192, "y": 740, "a": 60 }
        ],
        "crystals": [
          { "x": 393, "y": 624 },
          { "x": 305, "y": 1000 },
          { "x": 192, "y": 591 }
        ],
        "obstacles": [
          { "x": 220, "y": 820, "w": 200, "h": 100 },
          { "x": 540, "y": 780, "w": 100, "h": 240 }
        ]
      },
      {
        "name": "Citadel",
        "par": 3,
        "emitters": [
          { "x": 80, "y": 960, "dx": 1, "dy": 0 }
        ],
        "mirrors": [
          { "x": 372, "y": 960, "a": 120, "fixed": true },
          { "x": 132, "y": 544, "a": 120 },
          { "x": 312, "y": 232, "a": 135 },
          { "x": 572, "y": 382, "a": 150 },
          { "x": 540, "y": 940, "a": 165 }
        ],
        "crystals": [
          { "x": 349, "y": 768 },
          { "x": 240, "y": 356 },
          { "x": 236, "y": 960 }
        ],
        "obstacles": [
          { "x": 620, "y": 800, "w": 80, "h": 200 },
          { "x": 220, "y": 460, "w": 140, "h": 160 }
        ]
      }
    ]
  },
  {
    "id": "twin",
    "title": "Twin Suns",
    "subtitle": "Two lights, one harmony",
    "levels": [
      {
        "name": "Binary",
        "hint": "Two suns — every crystal must shine",
        "par": 2,
        "emitters": [
          { "x": 80, "y": 400, "dx": 1, "dy": 0 },
          { "x": 720, "y": 800, "dx": -1, "dy": 0 }
        ],
        "mirrors": [
          { "x": 592, "y": 400, "a": 120 },
          { "x": 288, "y": 800, "a": 150 }
        ],
        "crystals": [
          { "x": 592, "y": 835 },
          { "x": 288, "y": 294 }
        ],
        "obstacles": []
      },
      {
        "name": "Confluence",
        "par": 3,
        "emitters": [
          { "x": 640, "y": 1090, "dx": 0, "dy": -1 },
          { "x": 720, "y": 460, "dx": -1, "dy": 0 }
        ],
        "mirrors": [
          { "x": 640, "y": 638, "a": 135 },
          { "x": 432, "y": 518, "a": 45 },
          { "x": 128, "y": 460, "a": 15 }
        ],
        "crystals": [
          { "x": 572, "y": 276 },
          { "x": 227, "y": 289 },
          { "x": 640, "y": 849 }
        ],
        "obstacles": []
      },
      {
        "name": "Solstice",
        "par": 3,
        "emitters": [
          { "x": 260, "y": 230, "dx": 0, "dy": 1 },
          { "x": 80, "y": 640, "dx": 1, "dy": 0 }
        ],
        "mirrors": [
          { "x": 260, "y": 482, "a": 15 },
          { "x": 658, "y": 712, "a": 120 },
          { "x": 352, "y": 640, "a": 30 }
        ],
        "crystals": [
          { "x": 658, "y": 246 },
          { "x": 352, "y": 330 },
          { "x": 516, "y": 630 }
        ],
        "obstacles": [
          { "x": 480, "y": 300, "w": 80, "h": 260 }
        ]
      },
      {
        "name": "Equinox",
        "par": 3,
        "emitters": [
          { "x": 80, "y": 700, "dx": 1, "dy": 0 },
          { "x": 720, "y": 820, "dx": -1, "dy": 0 }
        ],
        "mirrors": [
          { "x": 572, "y": 700, "a": 45 },
          { "x": 682, "y": 509, "a": 15 },
          { "x": 168, "y": 820, "a": 45, "fixed": true },
          { "x": 168, "y": 420, "a": 15 }
        ],
        "crystals": [
          { "x": 324, "y": 302 },
          { "x": 453, "y": 255 },
          { "x": 168, "y": 608 }
        ],
        "obstacles": [
          { "x": 320, "y": 480, "w": 220, "h": 80 }
        ]
      },
      {
        "name": "Aurora",
        "par": 4,
        "emitters": [
          { "x": 720, "y": 440, "dx": -1, "dy": 0 },
          { "x": 80, "y": 980, "dx": 1, "dy": 0 }
        ],
        "mirrors": [
          { "x": 248, "y": 440, "a": 90 },
          { "x": 248, "y": 780, "a": 120 },
          { "x": 392, "y": 980, "a": 120 },
          { "x": 562, "y": 686, "a": 30 }
        ],
        "crystals": [
          { "x": 628, "y": 561 },
          { "x": 677, "y": 885 },
          { "x": 248, "y": 599 },
          { "x": 418, "y": 440 }
        ],
        "obstacles": [
          { "x": 100, "y": 520, "w": 80, "h": 180 }
        ]
      },
      {
        "name": "Parallax",
        "par": 3,
        "emitters": [
          { "x": 520, "y": 1090, "dx": 0, "dy": -1 },
          { "x": 80, "y": 980, "dx": 1, "dy": 0 }
        ],
        "mirrors": [
          { "x": 520, "y": 578, "a": 165 },
          { "x": 278, "y": 438, "a": 165 },
          { "x": 652, "y": 980, "a": 15 },
          { "x": 160, "y": 580, "a": 165 }
        ],
        "crystals": [
          { "x": 364, "y": 290 },
          { "x": 652, "y": 777 },
          { "x": 393, "y": 504 }
        ],
        "obstacles": [
          { "x": 420, "y": 300, "w": 180, "h": 100 },
          { "x": 240, "y": 580, "w": 200, "h": 80 }
        ]
      },
      {
        "name": "Zenith",
        "par": 4,
        "emitters": [
          { "x": 80, "y": 1020, "dx": 1, "dy": 0 },
          { "x": 240, "y": 230, "dx": 0, "dy": 1 }
        ],
        "mirrors": [
          { "x": 432, "y": 1020, "a": 30 },
          { "x": 622, "y": 691, "a": 90, "fixed": true },
          { "x": 512, "y": 500, "a": 60 },
          { "x": 240, "y": 782, "a": 150 },
          { "x": 569, "y": 972, "a": 30 }
        ],
        "crystals": [
          { "x": 126, "y": 723 },
          { "x": 647, "y": 837 },
          { "x": 427, "y": 890 },
          { "x": 278, "y": 1020 }
        ],
        "obstacles": [
          { "x": 360, "y": 240, "w": 260, "h": 80 },
          { "x": 380, "y": 640, "w": 160, "h": 120 }
        ]
      },
      {
        "name": "Sanctuary",
        "par": 5,
        "emitters": [
          { "x": 180, "y": 230, "dx": 0, "dy": 1 },
          { "x": 180, "y": 1090, "dx": 0, "dy": -1 }
        ],
        "mirrors": [
          { "x": 180, "y": 502, "a": 75 },
          { "x": 526, "y": 302, "a": 0 },
          { "x": 526, "y": 642, "a": 75 },
          { "x": 180, "y": 838, "a": 45 },
          { "x": 380, "y": 838, "a": 165 }
        ],
        "crystals": [
          { "x": 211, "y": 642 },
          { "x": 380, "y": 679 },
          { "x": 526, "y": 521 },
          { "x": 312, "y": 426 }
        ],
        "obstacles": [
          { "x": 220, "y": 920, "w": 240, "h": 100 },
          { "x": 580, "y": 720, "w": 120, "h": 200 }
        ]
      }
    ]
  }
];

/** Flat list with chapter info, in play order. */
export const LEVELS = CHAPTERS.flatMap((ch, ci) =>
  ch.levels.map((lvl, li) => ({ ...lvl, chapter: ci, chapterId: ch.id, indexInChapter: li })));
LEVELS.forEach((l, i) => { l.index = i; l.number = i + 1; });
