/*
 * Level generator.  Run:  node tools/generate-levels.mjs
 *
 *   tools/specs/<chapter>.mjs   what each chapter contains (one file per chapter)
 *   tools/lib/search.mjs        the candidate builder + brute-force search
 *   tools/solver.mjs            the solver both of them share
 *
 * Output: one file per chapter in js/levels/chapters/, plus nothing else — the
 * hand-written js/levels/index.js stitches them together in play order.
 */
import { writeFileSync, mkdirSync } from 'node:fs';
import { solve } from './solver.mjs';
import { generate } from './lib/search.mjs';
import dawn from './specs/dawn.mjs';
import monolith from './specs/monolith.mjs';
import twin from './specs/twin.mjs';

// Play order. Seeds advance per level in this order, so DON'T reorder (it would reshuffle every generated level).
const CHAPTER_SPECS = [dawn, monolith, twin];

const HEADER = (id) => `/*
 * AUTO-GENERATED by tools/generate-levels.mjs from tools/specs/${id}.mjs — do not edit by hand.
 * Every level here has been brute-force verified as solvable.
 *
 * Units: logical 800x1200 board. Mirror angle "a" is in degrees.
 * par = fewest mirrors that must be turned to win (3 stars at or under par).
 */
`;

const compact = (json) => json
  .replace(/\{\s+"x": (-?[\d.]+),\s+"y": (-?[\d.]+),\s+"dx": (-?[\d.]+),\s+"dy": (-?[\d.]+)\s+\}/g, '{ "x": $1, "y": $2, "dx": $3, "dy": $4 }')
  .replace(/\{\s+"x": (-?[\d.]+),\s+"y": (-?[\d.]+),\s+"a": (-?[\d.]+)(,\s+"fixed": true)?\s+\}/g, (m, x, y, a, f) => `{ "x": ${x}, "y": ${y}, "a": ${a}${f ? ', "fixed": true' : ''} }`)
  .replace(/\{\s+"x": (-?[\d.]+),\s+"y": (-?[\d.]+)\s+\}/g, '{ "x": $1, "y": $2 }')
  .replace(/\{\s+"x": (-?[\d.]+),\s+"y": (-?[\d.]+),\s+"w": (-?[\d.]+),\s+"h": (-?[\d.]+)\s+\}/g, '{ "x": $1, "y": $2, "w": $3, "h": $4 }');

mkdirSync(new URL('../js/levels/chapters/', import.meta.url), { recursive: true });

let seedBase = 1000, total = 0;
for (const ch of CHAPTER_SPECS) {
  const levels = [];
  for (const spec of ch.levels) {
    seedBase += 7919;
    let def;
    if (spec.handmade) {
      def = { ...ch.handmade[spec.handmade] };
      const res = solve(def);
      if (!res.solutions) throw new Error(`Handmade level ${spec.name} is unsolvable`);
      def.par = res.par; def.solutions = res.solutions; def.total = res.total;
    } else {
      def = generate(spec, seedBase);
      if (!def) throw new Error(`Could not generate ${spec.name}`);
    }
    levels.push({
      name: spec.name,
      ...(spec.hint ? { hint: spec.hint } : {}),
      par: def.par, emitters: def.emitters, mirrors: def.mirrors, crystals: def.crystals, obstacles: def.obstacles
    });
    console.log(`${ch.id.padEnd(9)} ${spec.name.padEnd(14)} par ${def.par}  solutions ${def.solutions}/${def.total}`);
  }
  const chapter = { id: ch.id, title: ch.title, subtitle: ch.subtitle, levels };
  const file = new URL(`../js/levels/chapters/${ch.id}.js`, import.meta.url);
  writeFileSync(file, HEADER(ch.id) + `export default ${compact(JSON.stringify(chapter, null, 2))};\n`);
  total += levels.length;
}
console.log(`\nWrote ${total} levels to js/levels/chapters/`);
